// GENERATED by tools/generate_model.py -- do not edit by hand.
// The texture assets/occupant/textures/entity/occupant.png is written by the same script,
// so these texture offsets and that image can never disagree.
package com.wolfsmask.occupant.client.render;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

import java.util.List;

/** The Occupant's body: a long pale face on a paper-thin body, carried on ten legs. */
public final class OccupantGeometry {
	/** The bones of the shroud it wears while it is still only a shape. */
	public static final List<String> SHROUD = List.of();
	/** Height of the built body in model pixels (16 = one block). */
	public static final float HEIGHT = 95.60f;
	/** How high the hips stand above the ground when it is upright, in model pixels. */
	public static final float HIPS_HEIGHT = 44.0f;
	public static final int LEGS = 10;
	/** Each leg's direction out from the body, in radians (model x = sin, model z = cos). */
	public static final float[] LEG_ANGLE = {0.3142f, 1.0912f, 1.3516f, 2.3733f, 2.7899f, 3.3368f, 4.2969f, 4.5178f, 5.4146f, 6.0547f};
	/** Each leg's full length, root to point, in model pixels. */
	public static final float[] LEG_LENGTH = {62.11f, 79.74f, 69.28f, 83.91f, 73.44f, 68.97f, 80.60f, 73.13f, 84.77f, 77.30f};
	/** How high each leg leaves the body, above the ground, standing upright, in model pixels. */
	public static final float[] LEG_ROOT_HEIGHT = {44.30f, 60.37f, 50.44f, 66.51f, 56.58f, 46.64f, 62.71f, 52.78f, 68.85f, 58.92f};
	/** Each leg's thigh, root to knee, in model pixels: where the knee is when the leg is solved. */
	public static final float[] LEG_UPPER = {27.02f, 35.71f, 31.01f, 36.70f, 31.99f, 30.28f, 35.97f, 31.26f, 36.96f, 35.25f};

	private OccupantGeometry() {
	}

	public static LayerDefinition create() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p;

		p = root.addOrReplaceChild("head", CubeListBuilder.create(), PartPose.offset(0.0f, -64.0f, 0.0f));
		PartDefinition p_head = p;
		p = p_head.addOrReplaceChild("hat", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_hat = p;
		p = root.addOrReplaceChild("body", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_body = p;
		p = root.addOrReplaceChild("right_arm", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_right_arm = p;
		p = root.addOrReplaceChild("left_arm", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_left_arm = p;
		p = root.addOrReplaceChild("right_leg", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_right_leg = p;
		p = root.addOrReplaceChild("left_leg", CubeListBuilder.create(), PartPose.ZERO);
		PartDefinition p_left_leg = p;
		p = root.addOrReplaceChild("hips", CubeListBuilder.create()
				.texOffs(230, 45).addBox(-2.50f, -1.0f, -1.0f, 5.0f, 6.0f, 2.0f), PartPose.offset(0.0f, -20.0f, 0.0f));
		PartDefinition p_hips = p;
		p = p_hips.addOrReplaceChild("spine", CubeListBuilder.create()
				.texOffs(208, 0).addBox(-2.25f, -30.0f, -0.80f, 4.50f, 30.0f, 1.60f), PartPose.offset(0.0f, -1.0f, 0.0f));
		PartDefinition p_spine = p;
		p = p_spine.addOrReplaceChild("yoke", CubeListBuilder.create()
				.texOffs(72, 76).addBox(-3.50f, -2.0f, -1.20f, 7.0f, 3.0f, 2.40f), PartPose.offset(0.0f, -30.0f, 0.0f));
		PartDefinition p_yoke = p;
		p = p_yoke.addOrReplaceChild("mantle", CubeListBuilder.create()
				.texOffs(242, 0).addBox(0.37f, 0.11f, 1.84f, 1.36f, 28.11f, 1.36f)
				.texOffs(148, 45).addBox(1.87f, 0.08f, 1.34f, 1.54f, 16.71f, 1.54f)
				.texOffs(140, 0).addBox(3.58f, 0.08f, 0.66f, 0.96f, 33.62f, 0.96f)
				.texOffs(96, 0).addBox(3.28f, 0.16f, 0.17f, 1.14f, 33.71f, 1.14f)
				.texOffs(112, 45).addBox(3.71f, 0.19f, -0.51f, 1.32f, 23.64f, 1.32f)
				.texOffs(136, 45).addBox(3.40f, 0.14f, -1.93f, 1.49f, 21.44f, 1.49f)
				.texOffs(160, 0).addBox(2.15f, 0.11f, -2.56f, 0.92f, 32.14f, 0.92f)
				.texOffs(44, 45).addBox(0.63f, 0.11f, -2.24f, 1.10f, 26.72f, 1.10f)
				.texOffs(52, 45).addBox(-1.67f, 0.11f, -3.70f, 1.28f, 26.40f, 1.28f)
				.texOffs(0, 45).addBox(-2.16f, 0.16f, -2.45f, 1.45f, 28.43f, 1.45f)
				.texOffs(144, 45).addBox(-4.50f, 0.08f, -1.81f, 0.88f, 21.82f, 0.88f)
				.texOffs(12, 45).addBox(-4.77f, 0.12f, -1.49f, 1.06f, 27.31f, 1.06f)
				.texOffs(60, 45).addBox(-5.31f, 0.08f, -0.16f, 1.23f, 26.76f, 1.23f)
				.texOffs(120, 45).addBox(-4.59f, 0.12f, 0.38f, 1.41f, 23.07f, 1.41f)
				.texOffs(104, 0).addBox(-3.12f, 0.11f, 1.68f, 1.59f, 33.14f, 1.59f)
				.texOffs(188, 0).addBox(-1.41f, 0.11f, 2.22f, 1.01f, 30.27f, 1.01f), PartPose.offset(0.0f, -1.50f, 0.0f));
		PartDefinition p_mantle = p;
		p = p_yoke.addOrReplaceChild("neck", CubeListBuilder.create()
				.texOffs(156, 45).addBox(-1.20f, -11.0f, -1.20f, 2.40f, 11.0f, 2.40f), PartPose.offset(0.0f, -1.50f, 0.40f));
		PartDefinition p_neck = p;
		p = p_neck.addOrReplaceChild("skull", CubeListBuilder.create()
				.texOffs(168, 45).addBox(-3.50f, -9.30f, -3.0f, 7.0f, 7.0f, 6.0f)
				.texOffs(50, 76).addBox(-2.75f, -10.40f, -2.40f, 5.50f, 1.10f, 4.80f), PartPose.offset(0.0f, -8.70f, -0.40f));
		PartDefinition p_skull = p;
		p = p_skull.addOrReplaceChild("jaw", CubeListBuilder.create()
				.texOffs(206, 45).addBox(1.75f, 0.0f, -2.95f, 1.70f, 6.0f, 3.35f)
				.texOffs(218, 45).addBox(-3.45f, 0.0f, -2.95f, 1.70f, 6.0f, 3.35f)
				.texOffs(244, 45).addBox(1.35f, 6.0f, -2.80f, 1.40f, 4.60f, 3.0f)
				.texOffs(0, 76).addBox(-2.75f, 6.0f, -2.80f, 1.40f, 4.60f, 3.0f)
				.texOffs(92, 76).addBox(-1.85f, 9.55f, -2.60f, 3.70f, 2.10f, 2.55f)
				.texOffs(194, 45).addBox(-1.74f, 0.02f, -2.0f, 3.48f, 9.56f, 1.90f)
				.texOffs(122, 76).addBox(-1.13f, 0.05f, -2.72f, 0.42f, 0.95f, 0.66f)
				.texOffs(126, 76).addBox(-0.55f, 0.05f, -2.70f, 0.43f, 0.78f, 0.64f)
				.texOffs(130, 76).addBox(0.04f, 0.05f, -2.71f, 0.41f, 0.92f, 0.65f)
				.texOffs(134, 76).addBox(0.62f, 0.05f, -2.69f, 0.44f, 0.74f, 0.63f)
				.texOffs(106, 76).addBox(-1.74f, 0.0f, -2.86f, 0.53f, 1.55f, 0.79f)
				.texOffs(110, 76).addBox(1.21f, 0.0f, -2.86f, 0.53f, 1.55f, 0.79f)
				.texOffs(114, 76).addBox(-1.33f, 8.15f, -2.84f, 0.48f, 1.42f, 0.77f)
				.texOffs(118, 76).addBox(0.85f, 8.15f, -2.84f, 0.48f, 1.42f, 0.77f), PartPose.offset(0.0f, -2.30f, 0.0f));
		PartDefinition p_jaw = p;
		p = p_skull.addOrReplaceChild("hair", CubeListBuilder.create()
				.texOffs(222, 0).addBox(-0.43f, -6.90f, 3.38f, 0.69f, 30.49f, 0.69f)
				.texOffs(196, 0).addBox(0.29f, -6.90f, 3.72f, 0.83f, 31.45f, 0.83f)
				.texOffs(164, 0).addBox(1.76f, -6.93f, 2.28f, 0.97f, 32.38f, 0.97f)
				.texOffs(112, 0).addBox(2.46f, -6.86f, 2.55f, 1.12f, 33.33f, 1.12f)
				.texOffs(168, 0).addBox(3.17f, -6.93f, 2.15f, 0.66f, 32.56f, 0.66f)
				.texOffs(226, 0).addBox(3.64f, -6.86f, 1.42f, 0.80f, 30.94f, 0.80f)
				.texOffs(8, 45).addBox(3.36f, -6.90f, 0.77f, 0.94f, 29.64f, 0.94f)
				.texOffs(68, 45).addBox(3.86f, -6.93f, -0.73f, 1.08f, 26.37f, 1.08f)
				.texOffs(92, 45).addBox(4.55f, -6.90f, -0.36f, 0.62f, 26.87f, 0.62f)
				.texOffs(76, 45).addBox(3.24f, -6.93f, -1.80f, 0.77f, 27.46f, 0.77f)
				.texOffs(128, 45).addBox(3.72f, -6.86f, -2.53f, 0.91f, 24.11f, 0.91f)
				.texOffs(96, 45).addBox(3.42f, -6.93f, -3.15f, 1.05f, 25.45f, 1.05f)
				.texOffs(80, 45).addBox(-4.61f, -6.90f, -3.71f, 0.98f, 27.14f, 0.98f)
				.texOffs(20, 45).addBox(-4.14f, -6.93f, -2.36f, 1.12f, 27.65f, 1.12f)
				.texOffs(132, 45).addBox(-4.42f, -6.90f, -1.84f, 0.67f, 24.44f, 0.67f)
				.texOffs(28, 45).addBox(-4.71f, -6.93f, -0.56f, 0.81f, 28.66f, 0.81f)
				.texOffs(108, 45).addBox(-4.24f, -6.90f, -0.20f, 0.95f, 25.38f, 0.95f)
				.texOffs(84, 45).addBox(-5.54f, -6.90f, 0.35f, 1.09f, 26.30f, 1.09f)
				.texOffs(104, 45).addBox(-4.84f, -6.90f, 1.67f, 0.63f, 26.83f, 0.63f)
				.texOffs(32, 45).addBox(-3.34f, -6.93f, 2.17f, 0.77f, 28.95f, 0.77f)
				.texOffs(230, 0).addBox(-2.67f, -6.86f, 2.50f, 0.92f, 30.48f, 0.92f)
				.texOffs(120, 0).addBox(-2.17f, -6.90f, 2.08f, 1.06f, 33.15f, 1.06f)
				.texOffs(128, 0).addBox(-1.47f, -6.90f, 3.40f, 0.60f, 34.39f, 0.60f), PartPose.offset(0.0f, -2.30f, 0.0f));
		PartDefinition p_hair = p;
		p = p_spine.addOrReplaceChild("leg0_upper", CubeListBuilder.create()
				.texOffs(36, 45).addBox(-0.72f, -0.60f, -0.72f, 1.45f, 27.62f, 1.45f), PartPose.offset(0.71f, 0.70f, 0.71f));
		PartDefinition p_leg0_upper = p;
		p = p_leg0_upper.addOrReplaceChild("leg0_lower", CubeListBuilder.create()
				.texOffs(234, 0).addBox(-0.55f, -0.50f, -0.55f, 1.10f, 29.59f, 1.10f), PartPose.offset(0.0f, 27.02f, 0.0f));
		PartDefinition p_leg0_lower = p;
		p = p_leg0_lower.addOrReplaceChild("leg0_claw", CubeListBuilder.create()
				.texOffs(10, 76).addBox(-0.35f, -0.30f, -0.35f, 0.70f, 6.30f, 0.70f), PartPose.offset(0.0f, 29.09f, 0.0f));
		PartDefinition p_leg0_claw = p;
		p = p_spine.addOrReplaceChild("leg1_upper", CubeListBuilder.create()
				.texOffs(48, 0).addBox(-0.82f, -0.60f, -0.82f, 1.64f, 36.31f, 1.64f), PartPose.offset(2.04f, -15.37f, 0.35f));
		PartDefinition p_leg1_upper = p;
		p = p_leg1_upper.addOrReplaceChild("leg1_lower", CubeListBuilder.create()
				.texOffs(24, 0).addBox(-0.60f, -0.50f, -0.60f, 1.20f, 38.53f, 1.20f), PartPose.offset(0.0f, 35.71f, 0.0f));
		PartDefinition p_leg1_lower = p;
		p = p_leg1_lower.addOrReplaceChild("leg1_claw", CubeListBuilder.create()
				.texOffs(14, 76).addBox(-0.37f, -0.30f, -0.37f, 0.75f, 6.30f, 0.75f), PartPose.offset(0.0f, 38.03f, 0.0f));
		PartDefinition p_leg1_claw = p;
		p = p_spine.addOrReplaceChild("leg2_upper", CubeListBuilder.create()
				.texOffs(172, 0).addBox(-0.76f, -0.60f, -0.76f, 1.52f, 31.61f, 1.52f), PartPose.offset(2.24f, -5.44f, 0.16f));
		PartDefinition p_leg2_upper = p;
		p = p_leg2_upper.addOrReplaceChild("leg2_lower", CubeListBuilder.create()
				.texOffs(144, 0).addBox(-0.65f, -0.50f, -0.65f, 1.31f, 32.77f, 1.31f), PartPose.offset(0.0f, 31.01f, 0.0f));
		PartDefinition p_leg2_lower = p;
		p = p_leg2_lower.addOrReplaceChild("leg2_claw", CubeListBuilder.create()
				.texOffs(18, 76).addBox(-0.40f, -0.30f, -0.40f, 0.79f, 6.30f, 0.79f), PartPose.offset(0.0f, 32.27f, 0.0f));
		PartDefinition p_leg2_claw = p;
		p = p_spine.addOrReplaceChild("leg3_upper", CubeListBuilder.create()
				.texOffs(32, 0).addBox(-0.85f, -0.60f, -0.85f, 1.71f, 37.30f, 1.71f), PartPose.offset(1.60f, -21.51f, -0.54f));
		PartDefinition p_leg3_upper = p;
		p = p_leg3_upper.addOrReplaceChild("leg3_lower", CubeListBuilder.create()
				.texOffs(8, 0).addBox(-0.58f, -0.50f, -0.58f, 1.16f, 41.71f, 1.16f), PartPose.offset(0.0f, 36.70f, 0.0f));
		PartDefinition p_leg3_lower = p;
		p = p_leg3_lower.addOrReplaceChild("leg3_claw", CubeListBuilder.create()
				.texOffs(22, 76).addBox(-0.42f, -0.30f, -0.42f, 0.84f, 6.30f, 0.84f), PartPose.offset(0.0f, 41.21f, 0.0f));
		PartDefinition p_leg3_claw = p;
		p = p_spine.addOrReplaceChild("leg4_upper", CubeListBuilder.create()
				.texOffs(152, 0).addBox(-0.80f, -0.60f, -0.80f, 1.59f, 32.59f, 1.59f), PartPose.offset(0.79f, -11.58f, -0.70f));
		PartDefinition p_leg4_upper = p;
		p = p_leg4_upper.addOrReplaceChild("leg4_lower", CubeListBuilder.create()
				.texOffs(80, 0).addBox(-0.63f, -0.50f, -0.63f, 1.26f, 35.95f, 1.26f), PartPose.offset(0.0f, 31.99f, 0.0f));
		PartDefinition p_leg4_lower = p;
		p = p_leg4_lower.addOrReplaceChild("leg4_claw", CubeListBuilder.create()
				.texOffs(26, 76).addBox(-0.44f, -0.30f, -0.44f, 0.89f, 6.30f, 0.89f), PartPose.offset(0.0f, 35.45f, 0.0f));
		PartDefinition p_leg4_claw = p;
		p = p_spine.addOrReplaceChild("leg5_upper", CubeListBuilder.create()
				.texOffs(200, 0).addBox(-0.74f, -0.60f, -0.74f, 1.48f, 30.88f, 1.48f), PartPose.offset(-0.45f, -1.64f, -0.74f));
		PartDefinition p_leg5_upper = p;
		p = p_leg5_upper.addOrReplaceChild("leg5_lower", CubeListBuilder.create()
				.texOffs(132, 0).addBox(-0.56f, -0.50f, -0.56f, 1.12f, 33.19f, 1.12f), PartPose.offset(0.0f, 30.28f, 0.0f));
		PartDefinition p_leg5_lower = p;
		p = p_leg5_lower.addOrReplaceChild("leg5_claw", CubeListBuilder.create()
				.texOffs(30, 76).addBox(-0.37f, -0.30f, -0.37f, 0.74f, 6.30f, 0.74f), PartPose.offset(0.0f, 32.69f, 0.0f));
		PartDefinition p_leg5_claw = p;
		p = p_spine.addOrReplaceChild("leg6_upper", CubeListBuilder.create()
				.texOffs(56, 0).addBox(-0.83f, -0.60f, -0.83f, 1.66f, 36.57f, 1.66f), PartPose.offset(-2.10f, -17.71f, -0.30f));
		PartDefinition p_leg6_upper = p;
		p = p_leg6_upper.addOrReplaceChild("leg6_lower", CubeListBuilder.create()
				.texOffs(16, 0).addBox(-0.61f, -0.50f, -0.61f, 1.22f, 39.13f, 1.22f), PartPose.offset(0.0f, 35.97f, 0.0f));
		PartDefinition p_leg6_lower = p;
		p = p_leg6_lower.addOrReplaceChild("leg6_claw", CubeListBuilder.create()
				.texOffs(34, 76).addBox(-0.39f, -0.30f, -0.39f, 0.78f, 6.30f, 0.78f), PartPose.offset(0.0f, 38.63f, 0.0f));
		PartDefinition p_leg6_claw = p;
		p = p_spine.addOrReplaceChild("leg7_upper", CubeListBuilder.create()
				.texOffs(180, 0).addBox(-0.77f, -0.60f, -0.77f, 1.55f, 31.86f, 1.55f), PartPose.offset(-2.26f, -7.78f, -0.14f));
		PartDefinition p_leg7_upper = p;
		p = p_leg7_upper.addOrReplaceChild("leg7_lower", CubeListBuilder.create()
				.texOffs(64, 0).addBox(-0.66f, -0.50f, -0.66f, 1.32f, 36.37f, 1.32f), PartPose.offset(0.0f, 31.26f, 0.0f));
		PartDefinition p_leg7_lower = p;
		p = p_leg7_lower.addOrReplaceChild("leg7_claw", CubeListBuilder.create()
				.texOffs(38, 76).addBox(-0.42f, -0.30f, -0.42f, 0.83f, 6.30f, 0.83f), PartPose.offset(0.0f, 35.87f, 0.0f));
		PartDefinition p_leg7_claw = p;
		p = p_spine.addOrReplaceChild("leg8_upper", CubeListBuilder.create()
				.texOffs(40, 0).addBox(-0.87f, -0.60f, -0.87f, 1.73f, 37.56f, 1.73f), PartPose.offset(-1.76f, -23.85f, 0.48f));
		PartDefinition p_leg8_upper = p;
		p = p_leg8_upper.addOrReplaceChild("leg8_lower", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-0.59f, -0.50f, -0.59f, 1.18f, 42.31f, 1.18f), PartPose.offset(0.0f, 36.96f, 0.0f));
		PartDefinition p_leg8_lower = p;
		p = p_leg8_lower.addOrReplaceChild("leg8_claw", CubeListBuilder.create()
				.texOffs(42, 76).addBox(-0.44f, -0.30f, -0.44f, 0.88f, 6.30f, 0.88f), PartPose.offset(0.0f, 41.81f, 0.0f));
		PartDefinition p_leg8_claw = p;
		p = p_spine.addOrReplaceChild("leg9_upper", CubeListBuilder.create()
				.texOffs(88, 0).addBox(-0.81f, -0.60f, -0.81f, 1.62f, 35.85f, 1.62f), PartPose.offset(-0.52f, -13.92f, 0.73f));
		PartDefinition p_leg9_upper = p;
		p = p_leg9_upper.addOrReplaceChild("leg9_lower", CubeListBuilder.create()
				.texOffs(72, 0).addBox(-0.64f, -0.50f, -0.64f, 1.28f, 36.55f, 1.28f), PartPose.offset(0.0f, 35.25f, 0.0f));
		PartDefinition p_leg9_lower = p;
		p = p_leg9_lower.addOrReplaceChild("leg9_claw", CubeListBuilder.create()
				.texOffs(46, 76).addBox(-0.36f, -0.30f, -0.36f, 0.72f, 6.30f, 0.72f), PartPose.offset(0.0f, 36.05f, 0.0f));
		PartDefinition p_leg9_claw = p;

		return LayerDefinition.create(mesh, 256, 256);
	}
}
