package com.wolfsmask.occupant.registry;

import com.wolfsmask.occupant.Occupant;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.entry.RegistryEntry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

/** Custom sounds. The audio files live in assets/occupant/sounds and are generated by tools/generate_assets.py. */
public final class ModSounds {
	/** Loud, dissonant hit used for jumpscares. */
	public static final RegistryEntry<SoundEvent> STINGER = register("stinger");
	/** Low, beating drone that plays when you notice it. */
	public static final RegistryEntry<SoundEvent> DRONE = register("drone");
	/** Slow breathing, very close. */
	public static final RegistryEntry<SoundEvent> BREATH = register("breath");
	/** Unintelligible whispering. */
	public static final RegistryEntry<SoundEvent> WHISPER = register("whisper");
	/** Three knocks on wood. */
	public static final RegistryEntry<SoundEvent> KNOCK = register("knock");
	/** A burst of radio static. */
	public static final RegistryEntry<SoundEvent> STATIC = register("static");

	private ModSounds() {
	}

	private static RegistryEntry<SoundEvent> register(String name) {
		Identifier id = Identifier.of(Occupant.MOD_ID, name);
		return Registry.registerReference(Registries.SOUND_EVENT, id, SoundEvent.of(id));
	}

	public static void init() {
		// Loading this class registers the sounds.
	}
}
