package com.wolfsmask.occupant.registry;

import com.wolfsmask.occupant.Occupant;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;

/** Custom sounds. The audio files live in assets/occupant/sounds and are generated by tools/generate_assets.py. */
public final class ModSounds {
	/** Loud, dissonant hit used for jumpscares. */
	public static final Holder<SoundEvent> STINGER = register("stinger");
	/** Low, beating drone that plays when you notice it. */
	public static final Holder<SoundEvent> DRONE = register("drone");
	/** Slow breathing, very close. */
	public static final Holder<SoundEvent> BREATH = register("breath");
	/** Unintelligible whispering. */
	public static final Holder<SoundEvent> WHISPER = register("whisper");
	/** Three knocks on wood. */
	public static final Holder<SoundEvent> KNOCK = register("knock");
	/** A burst of radio static. */
	public static final Holder<SoundEvent> STATIC = register("static");
	/** The score, three loops mixed live: a low drone, high bowed glass, and a pulse when it is close. */
	public static final Holder<SoundEvent> DREAD_LOW = register("dread_low");
	public static final Holder<SoundEvent> DREAD_HIGH = register("dread_high");
	public static final Holder<SoundEvent> DREAD_PULSE = register("dread_pulse");

	private ModSounds() {
	}

	private static Holder<SoundEvent> register(String name) {
		Identifier id = Occupant.id(name);
		return Registry.registerForHolder(BuiltInRegistries.SOUND_EVENT, id, SoundEvent.createVariableRangeEvent(id));
	}

	public static void init() {
		// Loading this class registers the sounds.
	}
}
